### ISSUE TITLE
Trading strategy

### ISSUE THREAD

**Issue by PatCH0816** [m1balcerak/labels#7]
Regarding the chapter "5 Trading strategy", it is not clear, what kind of labels are in use to learn the strategy. Is it the continuous labels? Or is it a probability of the model outputs?

**Comment by m1balcerak** [comment]
In order to present a wide spectrum of strategies (ranked performance-wise) you need some kind of weight generator. We used  Bayesian Optimization and HyperBand  (BOHB) which is already mentioned in the text in chapter 3.2. It optimizes monthly returns but makes many random guesses for a broad spectrum.

**Comment by PatCH0816** [comment]
Thanks for your feedback, we answered the question by ourself. We use the predicted labels to optimize the strategy weights.
